### PR TITLE
Non reactive handling of running state

### PR DESCRIPTION
**Pull request by samouwow**
This addresses many of the concerns raised by #65.

It does not attempt to solve any of the "halt" functionality, so reactive sequences and fallbacks are still going to play up a little.

### CODE REVIEW

**Comment by samouwow** [comment]
Main doesn't seem to be building, so I had to branch off HEAD~1.

Would it be possible to revert the latest commit and put it into a feature branch until it's building?

**Comment by samouwow** [comment]
Also, sorry about all the formatting changes. I ran rust linter and cleared up the cargo warnings on files I touched.

**Comment by besok** [comment]
yeah, that is fare point. the last commit needs to be pushed to the feature branch

**Comment by besok** [comment]
Thanks for the awesome PR

**Pull request merged**
